version: "2"

services:
  ubuntu_14.04: &wine
    image: andyneff/wine_msys64:ubuntu_14.04
    cap_add:
      - SYS_PTRACE
    build:  &wine_build
      context: .
      dockerfile: ubuntu_14.04.Dockerfile
    environment:
      - DISPLAY
      - WINEDEBUG=fixme-all,err-winediag,err-menubuilder
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - wine_ubuntu_14.04:/home/.user_wine
    network_mode: bridge
  ubuntu_16.04:
    <<: *wine
    image: andyneff/wine_msys64:ubuntu_16.04
    build:
      <<: *wine_build
      dockerfile: ubuntu_16.04.Dockerfile
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - wine_ubuntu_16.04:/home/.user_wine
  ubuntu_18.04:
    <<: *wine
    image: andyneff/wine_msys64:ubuntu_18.04
    build:
      <<: *wine_build
      dockerfile: ubuntu_18.04.Dockerfile
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - wine_ubuntu_18.04:/home/.user_wine
  debian_8:
    <<: *wine
    image: andyneff/wine_msys64:debian_8
    build:
      <<: *wine_build
      dockerfile: debian_8.Dockerfile
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - wine_debian_8:/home/.user_wine
  debian_9:
    <<: *wine
    image: andyneff/wine_msys64:debian_9
    build:
      <<: *wine_build
      dockerfile: debian_9.Dockerfile
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - wine_debian_9:/home/.user_wine
  fedora_27:
    <<: *wine
    image: andyneff/wine_msys64:fedora_27
    build:
      <<: *wine_build
      dockerfile: fedora_27.Dockerfile
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - wine_fedora_27:/home/.user_wine

volumes:
  wine_ubuntu_14.04:
  wine_ubuntu_16.04:
  wine_ubuntu_18.04:
  wine_debian_8:
  wine_debian_9:
  wine_fedora_27: